#! /bin/bash

[[ $MP ]] || MP=micropython

function run {
        echo "-> Run '$@'"
        "$@"
}

mv umsgpack/umsgpack_ext.py umsgpack/umsgpack_ext.tmp
run python3 test_umsgpack.py
mv umsgpack/umsgpack_ext.tmp umsgpack/umsgpack_ext.py

run python3 test_umsgpack_ext.py
run $MP test_umsgpack_ext.py
